name: DemoJob
on: [workflow_dispatch, push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: Run a one-line script
          run: echo Hello, world!
  second-job:
    runs-on: macos-13
    steps:
        - name: Run a one-line script
          run: echo Hello, world!       

